### ISSUE TITLE
Remove non-source files from repository

### ISSUE THREAD

**Issue by stephanepoirier** [wheresvic/zsearch#50]
The following non-source files are included in the repository:
leveldb/build_config.mk
leveldb/libleveldb.dylib
leveldb/libleveldb.dylib.1
leveldb/libleveldb.dylib.1.16

They should be removed + ignored.

**Comment by stephanepoirier** [comment]
Create pull request #51  for this issue.

**Comment by maximecaron** [comment]
Working on ZSearch ?
